"""
quantize_and_export.py - Full INT8 Post-Training Quantization & C Header Generator

Converts the trained Keras float model to:
1. Micro-Corner-Regressor INT8 TFLite model (< 80 KB).
2. C header array (corner_model_quantized.h) for direct deployment to ESP32 Classic firmware.
"""

from pathlib import Path
import numpy as np
import tensorflow as tf
import config
from dataset import get_representative_dataset

def quantize_model(
    keras_model_path: Path = config.FLOAT_MODEL_PATH,
    output_tflite_path: Path = config.TFLITE_INT8_PATH,
    output_c_header_path: Path = config.C_HEADER_PATH
):
    print("=" * 65)
    print("  QUANTIZING MICRO-CORNER-REGRESSOR TO FULL INT8")
    print("=" * 65)

    if not keras_model_path.exists():
        print(f"[ERROR] Keras model not found at {keras_model_path}")
        print("Please train the model first using python train.py")
        return

    print(f"Loading Keras model: {keras_model_path}")
    model = tf.keras.models.load_model(str(keras_model_path))

    # TFLite Converter
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = get_representative_dataset
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.float32 # Keep output float coordinates for easy sub-pixel math

    print("Quantizing model with representative calibration dataset...")
    tflite_quant_model = converter.convert()

    # Save .tflite
    output_tflite_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_tflite_path, "wb") as f:
        f.write(tflite_quant_model)

    file_size_kb = len(tflite_quant_model) / 1024.0
    print(f"\n[OK] INT8 TFLite Model saved to: {output_tflite_path}")
    print(f"     Model Size: {file_size_kb:.2f} KB (Target < {config.MAX_FLASH_BYTES / 1024:.0f} KB)")

    if file_size_kb > (config.MAX_FLASH_BYTES / 1024.0):
        print(f"[WARN] Model size exceeds target budget of {config.MAX_FLASH_BYTES / 1024:.0f} KB!")

    # Generate C Header file for ESP32
    output_c_header_path.parent.mkdir(parents=True, exist_ok=True)
    hex_lines = []
    for i, byte in enumerate(tflite_quant_model):
        if i % 12 == 0:
            hex_lines.append("\n  ")
        hex_lines.append(f"0x{byte:02x}, ")

    c_content = f"""// Auto-generated by TinyML_Segmentation/quantize_and_export.py
// Model: Micro-Corner-Regressor INT8
// Flash Size: {file_size_kb:.2f} KB

#ifndef CORNER_MODEL_QUANTIZED_H_
#define CORNER_MODEL_QUANTIZED_H_

#include <stdint.h>

#ifdef __cplusplus
extern "C" {{
#endif

extern const unsigned char g_corner_model_data[];
extern const unsigned int g_corner_model_data_len;

alignas(16) const unsigned char g_corner_model_data[] = {{
{''.join(hex_lines)}
}};

const unsigned int g_corner_model_data_len = {len(tflite_quant_model)};

#ifdef __cplusplus
}}
#endif

#endif // CORNER_MODEL_QUANTIZED_H_
"""

    with open(output_c_header_path, "w", encoding="utf-8") as f:
        f.write(c_content)

    print(f"[OK] C Header file saved to: {output_c_header_path}")
    print("Ready to compile with ESP-IDF or Arduino IDE for ESP32 Classic!")

if __name__ == "__main__":
    quantize_model()
